package com.simc.simc40.errorHandling;

public interface FirebaseDatabaseExceptionErrorList {
    String EXCEPTION_EMPTY_CLIENT_DATABASE = "ERROR_NO_CLIENT_REGISTERED";
    String EXCEPTION_EMPTY_CLIENT_DATABASE_ADMIN = "ERROR_NO_CLIENT_REGISTERED";
    String EXCEPTION_CLIENT_NOT_FOUND = "ERROR_CLIENT_NOT_FOUND";
    String EXCEPTION_USER_WITH_NO_CLIENT = "ERROR_USER_WITH_NO_CLIENT";
    String EXCEPTION_NULL_DATABASE_OBRAS = "EXCEPTION_NULL_DATABASE_OBRAS";
    String EXCEPTION_NULL_DATABASE_ELEMENTOS = "EXCEPTION_NULL_DATABASE_ELEMENTOS";
    String EXCEPTION_NULL_DATABASE_GALPOES = "EXCEPTION_NULL_DATABASE_GALPOES";
    String EXCEPTION_NULL_CONTROLE_GALPAO = "EXCEPTION_NULL_CONTROLE_GALPAO";
    String EXCEPTION_NULL_DATABASE_TRANSPORTADORAS = "EXCEPTION_NULL_DATABASE_TRANSPORTADORAS";
    String EXCEPTION_TRANSPORTADORA_NULL_VEICULOS_AND_MOTORISTAS = "EXCEPTION_TRANSPORTADORA_NULL_VEICULOS_AND_MOTORISTAS";
    String EXCEPTION_NULL_DATABASE_VEICULOS = "EXCEPTION_NULL_DATABASE_VEICULOS";
    String EXCEPTION_NULL_DATABASE_ROMANEIOS = "EXCEPTION_NULL_DATABASE_ROMANEIOS";
    String EXCEPTION_NULL_DATABASE_FORMAS = "EXCEPTION_NULL_DATABASE_FORMAS";
    String EXCEPTION_NULL_DATABASE_USERS = "EXCEPTION_NULL_DATABASE_USERS";
    String EXCEPTION_USER_NOT_FOUND = "ERROR_USER_NOT_FOUND";
    String EXCEPTION_CLIENT_WITH_INACTIVE_STATUS = "ERROR_CLIENT_WITH_INACTIVE_STATUS";
    String EXCEPTION_TIME_LIMIT_REACHED = "ERROR_TIME_LIMIT_REACHED";
    String EXCEPTION_RETURNED_NULL_VALUE = "ERROR_RETURNED_NULL_VALUE";
    String EXCEPTION_POST_FAILED = "EXCEPTION_POST_FAILED";
}
