package com.simc.simc40.errorHandling;

public interface QualidadeExceptionErrorList {
    String EXCEPTION_OBRA_NULL = "ERROR_OBRA_NULL";
    String EXCEPTION_ELEMENTO_NULL = "ERROR_ELEMENTO_NULL";
    String EXCEPTION_NO_REGISTERED_ELEMENTOS = "ERROR_NO_REGISTERED_ELEMENTOS";
    String EXCEPTION_NO_REGISTERED_PECAS = "ERROR_NO_REGISTERED_PECAS";
    String EXCEPTION_NO_REGISTERED_PDF_IN_OBRA = "ERROR_NO_REGISTERED_PDF_IN_OBRA";
    String EXCEPTION_NO_REGISTERED_PDF_IN_ELEMENTO = "ERROR_NO_REGISTERED_PDF_IN_ELEMENTO";
    String EXCEPTION_MULTIPLE_SELECTED_TAGS = "ERROR_MULTIPLE_SELECTED_TAGS";
    String EXCEPTION_INPUT_FIELDS_ARE_NOT_VALID = "ERROR_INPUT_FIELDS_ARE_NOT_VALID";
    String EXCEPTION_TAG_NOT_FOUND = "EXCEPTION_TAG_NOT_FOUND";
    String EXCEPTION_TAG_ALREADY_REGISTERED = "EXCEPTION_TAG_ALREADY_REGISTERED";
    String EXCEPTION_NO_SELECTED_TAG_ON_SUBMIT = "EXCEPTION_NO_SELECTED_TAG_ON_SUBMIT";
    String EXCEPTION_MAX_POSSIBLE_READ_PECAS_REACHED = "EXCEPTION_MAX_POSSIBLE_READ_PECAS_REACHED";
    String EXCEPTION_MAX_REGISTERED_PECAS_REACHED = "EXCEPTION_MAX_REGISTERED_PECAS_REACHED";
    String EXCEPTION_REPORTAR_ERRO_TAG_NO_ITEM_REGISTERED = "EXCEPTION_REPORTAR_ERRO_TAG_NO_ITEM_REGISTERED";
    String EXCEPTION_REPORTAR_ERRO_ITEM_NO_COMENTARIO_REGISTERED = "EXCEPTION_REPORTAR_ERRO_ITEM_NO_COMENTARIO_REGISTERED";
    String EXCEPTION_CHECKLIST_NOT_FILLED = "EXCEPTION_CHECKLIST_NOT_FILLED";
    String EXCEPTION_PRODUCAO_INTERRUPTED = "EXCEPTION_PRODUCAO_INTERRUPTED";
    String EXCEPTION_GALPAO_NOT_FILLED = "EXCEPTION_GALPAO_NOT_FILLED";
    String EXCEPTION_CARGA_PASSED = "EXCEPTION_CARGA_PASSED";
    String EXCEPTION_TRANSPORTE_PASSED = "EXCEPTION_TRANSPORTE_PASSED";
    String EXCEPTION_ROMANEIO_FINISHED = "EXCEPTION_ROMANEIO_FINISHED";
    String EXCEPTION_CARGA_NOT_READY = "EXCEPTION_CARGA_NOT_READY";
    String EXCEPTION_TRANSPORTE_NOT_READY = "EXCEPTION_TRANSPORTE_NOT_READY";
}
