package com.simc.simc40.errorHandling;

public interface ReaderExceptionErrorList {
    String EXCEPTION_READER_NOT_SELECTED = "EXCEPTION_READER_NOT_SELECTED";
    String EXCEPTION_READER_NOT_CONFIGURED = "ERROR_READER_NOT_CONFIGURED";
    String EXCEPTION_API_VERSION_NOT_CONFIGURED = "EXCEPTION_API_VERSION_NOT_CONFIGURED";
    String EXCEPTION_TAG_FORMAT_INVALID = "EXCEPTION_TAG_FORMAT_INVALID";
    String EXCEPTION_UNREGISTERED_TAG = "EXCEPTION_UNREGISTERED_TAG";
    String EXCEPTION_WRONG_ETAPA = "EXCEPTION_WRONG_ETAPA";
    String EXCEPTION_TAG_ALREADY_READED = "EXCEPTION_TAG_ALREADY_READED";
    String EXCEPTION_TAG_WITH_NO_ROMANEIO = "EXCEPTION_TAG_WITH_NO_ROMANEIO";
    String EXCEPTION_TAG_NOT_REGISTED_IN_ROMANEIO = "EXCEPTION_TAG_NOT_REGISTED_IN_ROMANEIO";
    String EXCEPTION_WRONG_READING_TYPE = "EXCEPTION_WRONG_READING_TYPE";

}
