package com.android.simc40.errorHandling;

public interface FirebaseDatabaseExceptionErrorList {
    String EXCEPTION_EMPTY_CLIENT_DATABASE = "ERROR_NO_CLIENT_REGISTERED";
    String EXCEPTION_EMPTY_CLIENT_DATABASE_ADMIN = "ERROR_NO_CLIENT_REGISTERED";
    String EXCEPTION_CLIENT_NOT_FOUND = "ERROR_CLIENT_NOT_FOUND";
    String EXCEPTION_USER_WITH_NO_CLIENT = "ERROR_USER_WITH_NO_CLIENT";
    String EXCEPTION_USER_NOT_FOUND = "ERROR_USER_NOT_FOUND";
    String EXCEPTION_CLIENT_WITH_INACTIVE_STATUS = "ERROR_CLIENT_WITH_INACTIVE_STATUS";
    String EXCEPTION_TIME_LIMIT_REACHED = "ERROR_TIME_LIMIT_REACHED";
    String EXCEPTION_RETURNED_NULL_VALUE = "ERROR_RETURNED_NULL_VALUE";
}
