package com.android.simc40.errorHandling;

public interface PermissionExceptionList {
    String EXCEPTION_CAMERA_PERMISSION_DENIED = "ERROR_CAMERA_PERMISSION_DENIED";
    String EXCEPTION_GALLERY_PERMISSION_DENIED = "ERROR_GALLERY_PERMISSION_DENIED";
    String EXCEPTION_CAMERA_FILE_NULL = "EXCEPTION_CAMERA_FILE_NULL";
    
}
