package com.android.simc40.errorHandling;

public interface QualidadeExceptionErrorList {
    String EXCEPTION_OBRA_NULL = "ERROR_OBRA_NULL";
    String EXCEPTION_ELEMENTO_NULL = "ERROR_ELEMENTO_NULL";
    String EXCEPTION_NO_REGISTERED_ELEMENTOS = "ERROR_NO_REGISTERED_ELEMENTOS";
    String EXCEPTION_NO_REGISTERED_PDF_IN_OBRA = "ERROR_NO_REGISTERED_PDF_IN_OBRA";
    String EXCEPTION_NO_REGISTERED_PDF_IN_ELEMENTO = "ERROR_NO_REGISTERED_PDF_IN_ELEMENTO";
    String EXCEPTION_MULTIPLE_SELECTED_TAGS = "ERROR_MULTIPLE_SELECTED_TAGS";
    String EXCEPTION_INPUT_FIELDS_ARE_NOT_VALID = "ERROR_INPUT_FIELDS_ARE_NOT_VALID";
    String EXCEPTION_TAG_NOT_FOUND = "EXCEPTION_TAG_NOT_FOUND";
}
